GreenProject/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.community, name='community'),                            # post 리스트
    path('<int:post_id>/', views.detail, name='detail'),                    # post_id로 상세보기
    path('write/', views.post_create, name='post_create'),                  # post 작성
    path('edit/<int:post_id>/', views.post_edit, name='post_edit'),         # post 수정
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),   # post_id로 삭제
    path('category/<str:slug>/', views.category_page, name='cate_page'),    # 카테고리페이지(slug기능)
    path('likes/', views.post_like, name='post_like'),                      # 추천
]

GreenProject/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from greenbooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("gbook/mypage", views.mypage, name='mypage'),
    path('common/', include('common.urls')),
    path('community/', include('community.urls')),  # 커뮤니티
    path('tradebook/', include('tradebook.urls')),
    path('mypage/', include('mypage.urls')),
    path("goods/", include("goods.urls")),
    path('custom/', include('custom.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),   # 편집기
    path('price/', include('checkbookprice.urls')), # 바코드가격조회
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

GreenProject/goods/urls.py
from django.urls import path

from . import views

app_name = 'goods'


urlpatterns = [
    path('', views.goods_in_category, name='goods'),  # 구매페이지
    path('<slug:category_slug>/', views.goods_in_category, name='goods_in_category'),
    path('<int:id>/<goods_slug>/', views.goods_detail, name='goods_detail'),



    ]

GreenProject/community/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# 카테고리 모델
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)     # 카테고리 이름 - 중복불가
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)    # url과 연동, 중복불가, 유니코드(한글포함)가능

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return f'/community/category/{self.slug}'   # 카테고리에 해당하는 절대 slug형 url을 반환
        return reverse('community:cate_page', args=[self.slug])     # reverse 방식으로 변경

    class Meta:     # 중첩모델
        verbose_name = 'category'
        verbose_name_plural = 'categories'  # 복수형 단어 직접 지정


class Post(models.Model):   # 포스트 모델
    title = models.CharField(max_length=200)    # 제목: Char필드는 제한필요(최대=한글100자)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)  # 글쓴이: FK, User모델에서 가져옴 삭제연동
    create_date = models.DateTimeField(auto_now_add=True)       # 생성일: 최초 생성시 자동생성, 수정시 변경안됨
    modify_date = models.DateTimeField(null=True, blank=True)   # 수정일: 수동생성(null/공백 가능)
    views = models.PositiveIntegerField(default=0)      # 조회수 - 양수만 입력가능하도록 positive 추가
    # 카테고리: FK(null/공백 가능, 삭제비연동)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    # 포스트추천인: 1사용자 - 여러 포스트 추천, 1포스트 - 여러 사용자의 추천 연결이 가능하도록 다대다필드
    liked_user = models.ManyToManyField(User, related_name='likes', blank=True)
    # 편집기 연결: 내용과 파일첨부를 대체
    description = RichTextUploadingField()

    def __str__(self):
        return self.title   # Post를 식별할 상황에서 기본인 id가 아니라 title값을 불러와줘서 알아보기 쉽게 함

    # 조회수 증가: 주훈씨 모델링 참고함. @property: 메서드를 속성처럼 사용할 수 있도록 해주는 데코레이터
    @property
    def update_views(self):
        self.views += 1
        self.save()
        return self.views

    # 포스트의 추천인 수
    def count_liked_user(self):
        return self.liked_user.count()

GreenProject/community/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):    # 폼 생성시 필요한 필드
    class Meta:
        model = Post
        fields = ['title', 'category', 'description']     # 편집기 버전
        labels = {  # 유효성 검사시 영어인 필드이름을 한글로 뜨도록
            'title': '제목',
            'category': '분류',
            'description': '내용',
        }

GreenProject/community/views.py
import json
from datetime import date

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.http import require_POST

from community.forms import PostForm
from community.models import Post, Category


# post 리스트 페이지
def community(request):
    post_list = Post.objects.order_by('-create_date')   # 내림차순, 새로운 글이 맨위로 가도록 설정
    categories = Category.objects.all()                 # 카테고리 가져오기
    today = date.today()                                # 작성일과 비교하기 위해 오늘날짜 준비
    page = request.GET.get('page', '1')                 # 페이지 처리 시작 - 페이지 가져오기
    paginator = Paginator(post_list, 10)                # 장고내장모듈을 통해 페이지처리. 10개가 1페이지
    page_obj = paginator.get_page(page)                 # 페이지 처리한 리스트
    context = {'post_list': page_obj, 'categories': categories, 'today': today}    # 보낼 준비
    return render(request, 'community/community.html', context)     # 가져와서, 템플릿에 연결, 가져와야 할 것


# post 상세보기(post_id 필요)
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)  # post_id를 pk로 함
    post.update_views                       # 조회수 증가
    categories = Category.objects.all()     # 카테고리 추가
    has_liked = request.user in post.liked_user.all() if request.user.is_authenticated else False
    context = {'post': post, 'categories': categories, 'has_liked': has_liked}    # 업데이트한 정보들 전달하기
    return render(request, 'community/detail_ck.html', context)


# post 생성하기
@login_required(login_url='common:login')   # 로그인요구-로그인페이지연결
def post_create(request):
    categories = Category.objects.all()     # 카테고리 가져오기
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():     # 폼이 유효하면
            post = form.save(commit=False)  # 폼 가저장 후
            post.writer = request.user      # writer를 user로 지정하고
            form.save()     # 폼 저장
            return redirect('community:community')  # 목록페이지로 넘어가기
    else:   # get 방식으로 폼이 넘어왔을 때
        form = PostForm()   # 빈 폼 가져오기
    context = {'form': form, 'categories': categories}
    return render(request, 'community/post_form_ck.html', context)


# post 수정하기(post_id 필요)
@login_required(login_url='common:login')
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id, writer=request.user)     # post_id를 pk로 함     # writer를 user로 지정
    categories = Category.objects.all()
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)    # post의 정보를 가져옴
        if form.is_valid():                     # 유효성검사 후
            post = form.save(commit=False)      # 가저장
            post.modify_date = timezone.now()   # 수정일을 지정
            post.save()                         # 찐저장
            return redirect('community:detail', post_id=post_id)    # 수정한 post 페이지로 넘어가기
    else:
        form = PostForm(instance=post)
    context = {'form': form, 'categories':categories}    # 생성되었던 그대로의 post의 정보 form
    return render(request, 'community/post_form_ck.html', context)


# post 삭제하기(post_id 필요)
@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)  # post_id를 pk로 함
    post.delete()                               # 삭제하기(장고명령어)
    return redirect('community:community')      # 목록페이지로 넘어가기


# 카테고리 페이지 처리 메서드
def category_page(request, slug):
    current_category = Category.objects.get(slug=slug)  # 현재 카테고리 정보
    filter_list = Post.objects.filter(category=current_category)    # 현재 카테고리로 post 필터링
    post_list = filter_list.order_by('-create_date')    # 필터링된 post를 생성일 기준 내림차순 정렬
    categories = Category.objects.all()     # 전체 카테고리 정보
    page = request.GET.get('page', '1')     # 페이지 처리 시작 - 여기에서도 해주어야 start_index를 받아 올 수 있음
    paginator = Paginator(post_list, 10)    # 장고내장모듈을 통해 페이지처리. 10개가 1페이지
    page_obj = paginator.get_page(page)
    context = {'current_category': current_category, 'post_list': page_obj, 'categories': categories}
    return render(request, 'community/community.html', context)


@login_required(login_url='common:login')
@require_POST
def post_like(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    user = request.user                 # 유저: 현재 로그인한 유저
    if post.liked_user.filter(id=user.id).exists():  # 추천인 중에 유저가 존재할 때(이미 추천했을 때)
        post.liked_user.remove(user)    # liked_user에서 유저 제거
        liked = False
    else:   # 추천인 중에 유저가 없을 때(추천하지 않았을 때)
        post.liked_user.add(user)            # liked_user에 유저 추가
        liked = True
    context = {'likes_count': post.count_liked_user(), 'liked': liked}   # 해당 포스트 추천인 수 전달
    return HttpResponse(json.dumps(context), content_type='application/json')   # 정보를 json형태로 반환

GreenProject/templates/community/community.html
{% extends 'base.html' %}
<!-- 템플릿 필터 적용을 위해 추가 -->
{% load community_filter %}
{% load static %}
{%block title%} - 커뮤니티{%endblock%}
{% block content %}
<div class="container px-4 py-5">
    <!-- 공지사항 영역 -->
    <div id="announcement">
        <h2 class="pb-2 border-bottom">커뮤니티</h2>
        <p>공지사항: 독후감을 써주세요. 1등 회원에겐 상품을 드립니다.</p>
    </div>
    <!-- 그리드로 배치 -->
    <div class="row">
        <!-- 성길씨 Q&A에서 가져옴. 그리드: 왼쪽 2/12(16.67%) 영역 -->
        <!-- class = left-menu 삭제 -->
        <aside class="col-lg-2">
            <!-- class=p-3 bg-white style=width: 180px; 삭제 -->
            <div class="flex-shrink-0" style="font-size: 16px;">
                <ul class="list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse"
                                data-bs-target="#home-collapse" aria-expanded="true">
                            <!-- 카테고리 눌렀다면 사이드바 큰 글씨로 -->
                            {% if current_category.slug %}
                            <h3>{{ current_category.slug }}</h3>
                            {% else %}
                            <!-- 카테고리를 누르지 않았다면 -->
                            <h3>전체글</h3>
                            {% endif %}
                        </button>
                        <div class="collapse show" id="home-collapse" style="">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <!-- 전체글 -->
                                <li><a href="{% url 'community:community' %}" class="link-dark rounded">전체글</a></li>
                                <!-- 카테고리 이름으로 리스트 설정 -->
                                {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}" class="link-dark rounded">
                                    {{ category.name }}
                                </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </aside>
        <!-- 그리드: 가운데 8/12(66.67%) 영역 -->
        <!-- 편집기 크기와 테이블 크기 맞춤 -->
        <section id="community" class="col-lg-8">
            <table id="commu-table" class="table table-hover">
                <thead>
                    <tr>
                        <td>번호</td>
                        <!-- 카테고리 추가 -->
                        <td>카테고리</td>
                        <td>제목</td>
                        <td>작성자</td>
                        <td>작성일</td>
                        <td>조회</td>
                        <td>추천</td>
                    </tr>
                </thead>
                <tbody>
                    <!-- post가 있으면 -->
                    {% if post_list %}
                        <!-- 각 post별로 모두 -->
                        {% for post in post_list %}
                        <tr>
                            <!-- 번호 -->
                            <!-- 템플릿 태그 -->
                            <td>
                                {{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}
                            </td>
                            <!-- 카테고리 -->
                            <td>
                                {% if post.category %}
                                {{ post.category }}
                                {% endif %}
                            </td>
                            <!-- 제목: a태그로 연결 -->
                            <td>
                                <a href="{% url 'community:detail' post.id %}">
                                    {{ post.title }}
                                </a>
                            </td>
                            <!-- 작성자 -->
                            <td>{{ post.writer }}</td>
                            <!-- 작성일 -->
                            <!-- 오늘 작성된 글은 [오전/오후 hh:mm]으로 포맷변경 -->
                            {% if post.create_date|date:"Y-m-d" == today|date:"Y-m-d" %}
                                <td>{{ post.create_date|date:"A h:i" }}</td>
                            <!-- 오늘 글이 아니면 [yyyy.mm.dd]으로 포맷변경 -->
                            {% else %}
                                <td>{{ post.create_date|date:"Y.m.d" }}</td>
                            {% endif %}
                            <!-- 조회수 -->
                            <td>{{ post.views }}</td>
                            <!-- 좋아요 -->
                            <td>{{ post.count_liked_user }}</td>
                        </tr>
                        {% endfor %}
                    <!-- post가 없으면 -->
                    {% else %}
                    <tr>
                        <td colspan="6" class="text-center">게시글이 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
            <!-- 페이지 처리 영역 -->
            <ul class="pagination justify-content-center">
                <!-- 이전 페이지 -->
                {% if post_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ post_list.previous_page_number }}">
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="">
                {% endif %}
                        <i class="fa-solid fa-backward"></i>
                    </a>
                </li>
                <!-- 현재 페이지 -->
                {% for page_number in post_list.paginator.page_range %}
                    {% if page_number == post_list.number %}
                    <li class="page-item active">
                    {% else %}
                    <li class="page-item">
                    {% endif %}
                        <a class="page-link" href="?page={{ page_number }}">
                            {{ page_number }}
                        </a>
                    </li>
                {% endfor %}
                <!-- 다음 페이지 -->
                {% if post_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ post_list.next_page_number }}">
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="">
                {% endif %}
                        <i class="fa-solid fa-forward"></i>
                    </a>
                </li>
            </ul>
            <!-- 로그인시에만 글쓰기 버튼 보이게 -->
            {% if user.is_authenticated %}
            <!-- 마진탑 -->
            <div id="btn_write" class="text-end mt-3">
                <a href="{% url 'community:post_create' %}" class="btn-a btn btn-primary">글쓰기</a>
            </div>
            {% endif %}
        </section>
        <!-- 그리드: 오른쪽 2/12(16.67%) 영역 - 여백으로 남음 -->
    </div>
</div>
{% endblock %}

GreenProject/templates/community/detail_ck.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container px-4 py-5">
    <div id="announcement">
        <h2 class="pb-2 border-bottom">내용보기</h2>
        <p></p>
    </div>
    <div class="row">
        <!-- 성길씨 Q&A에서 가져옴. 그리드: 왼쪽 2/12(16.67%) 영역 -->
        <aside class="col-lg-2">
            <div class="flex-shrink-0" style="font-size: 16px;">
                <ul class="list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse"
                                data-bs-target="#home-collapse" aria-expanded="true">
                            <!-- 카테고리 눌렀다면 사이드바 큰 글씨로 -->
                            {% if current_category.slug %}
                            <h3>{{ current_category.slug }}</h3>
                            {% else %}
                            <!-- 카테고리를 누르지 않았다면 -->
                            <h3>전체글</h3>
                            {% endif %}
                        </button>
                        <div class="collapse show" id="home-collapse" style="">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <!-- 전체글 -->
                                <li><a href="{% url 'community:community' %}" class="link-dark rounded">전체글</a></li>
                                <!-- 카테고리 이름으로 리스트 설정 -->
                                {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}" class="link-dark rounded">
                                    {{ category.name }}
                                </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </aside>
        <!-- 그리드: 가운데 8/12(66.67%) 영역 -->
        <section id="detail" class="col-lg-8">
            <table class="table">
                <!-- [카테고리] 제목 -->
                <tr>
                    <th colspan="4">
                    {% if post.category %}
                    <!-- 카테고리가 있으면 카테고리를 제목 옆에 -->
                        <span id="commu-cate">[{{ post.category }}]</span>&nbsp;{{ post.title }}
                    {% else %}
                    <!-- 카테고리가 없으면 제목만 -->
                        {{ post.title }}
                    {% endif %}
                    </th>
                </tr>
                <!-- post 정보 -->
                <tr>
                    <!-- 글쓴이 -->
                    <td>글쓴이: {{ post.writer }}</td>
                    <!-- 수정된 경우 수정일시와 작성일시를, 아닌 경우 작성일시만 표시 -->
                    <!-- yy-m-d h:mm으로 포맷변경 -->
                    <td>
                        작성: {{ post.create_date|date:"y-n-j G:i" }}
                        {% if post.modify_date %}
                        ,&nbsp;&nbsp;수정: {{ post.modify_date|date:"y-n-j G:i" }}
                        {% endif %}
                    </td>
                    <!-- 조회수 -->
                    <td>조회: {{ post.views }}</td>
                    <!-- 추천버튼과 추천수 -->
                    <td>
                        <!-- 추천버튼 영역: 클래스지정-자바스크립트에 클릭시 함수적용, 네임지정-자바스크립트에 포스트정보 제공 -->
                        <button type="button" name="{{ post.id }}" class="like">
                            <!-- 현재 유저가 추천인 중에 있으면 -->
                            {% if has_liked %}
                            <img src="{% static 'greenbooks/images/heart_filled.png' %}" style="width: 20px; height: 20px;" alt="추천완료">
                            {% else %}
                            <img src="{% static 'greenbooks/images/heart_empty.png' %}" style="width: 20px; height: 20px;" alt="추천보류">
                            {% endif %}
                        </button>
                        <!-- 추천수 영역: id지정-정보받아서 ajax로 반영 -->
                        <span id="count-{{ post.id }}">{{ post.count_liked_user }}</span>
                    </td>
                </tr>
                <tr>
                <!-- post 내용 - 편집기 넣은 버전 -->
                    <!-- 스타일: 왼쪽정렬, 자동줄바꿈 적용되기 때문에 white-space처리 삭제 -->
                    <td colspan="4" class="text-start">
                        {{ post.description|safe }}
                    </td>
                </tr>
            </table>
        </section>
    </div>
    <!-- 마진탑 -->
    <div id="btn" class="text-center mt-3">
        <!-- post작성자가 자기 글을 봤을 때 - 삭제, 수정 -->
        {% if post.writer == request.user %}
            <!-- 삭제시 자바스크립트 연결 -->
        <a href="#"
           data-uri="{% url 'community:post_delete' post.id %}"
           class="delete btn-a btn btn-primary">삭제</a>
        <a href="{% url 'community:community' %}" class="btn-a btn btn-primary">목록</a>
        <a href="{% url 'community:post_edit' post.id %}" class="btn-a btn btn-primary">수정</a>
        <!-- post작성자가 아닌 사람이 글을 봤을 때 -->
        {% else %}
        <a href="{% url 'community:community' %}" class="btn-a btn btn-primary">목록</a>
        {% endif %}
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function() {
        // 삭제시 경고창
        // delete 클래스를 클릭시
        $('.delete').click(function() {
            // 경고창
            if(confirm('정말 삭제하시겠습니까?')) {
                // uri로 이동
                location.href=$(this).data('uri');
            }
        });

        // 추천 ajax처리
        $(".like").click(function () {
            var button = $(this);   // 버튼 특정하기
            var pk = button.attr('name');   // 버튼 name에서 post.id 가져오기
            $.ajax({
                type: "POST",
                url: "{% url 'community:post_like' %}",     // data를 전송할 url(뷰가 연결됨) 지정
                data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },  // pk를 통해 post 특정
                dataType: "json",   // json형식으로 data를 보냄
                success: function (response) {  // 전송 성공시
                    var likesCount = response.likes_count;  // 뷰에서 넘어온 likes_count정보
                    $("#count-" + pk).html(likesCount);     //id가 count인 영역에 likes_count 정보 가져오기
                    if (response.liked) {               // 버튼 영역에 정보 가져오기. 정보에 따라 상태 바꾸기
                        button.find('img').attr('src', '{% static 'greenbooks/images/heart_filled.png' %}');
                        button.find('img').attr('alt', '추천완료');
                    } else {
                        button.find('img').attr('src', '{% static 'greenbooks/images/heart_empty.png' %}');
                        button.find('img').attr('alt', '추천보류');
                    }
                },
                error: function (error) { // In case of transmission failure
                    console.error(error); // error message to console
                }
            });
        });
    })
</script>
{% endblock %}

GreenProject/templates/community/post_form_ck.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container px-4 py-5">
    <div id="announcement">
        <h2 class="pb-2 border-bottom">글남기기</h2>
        <p></p>
    </div>
    <div class="row">
        <!-- 성길씨 Q&A에서 가져옴. 그리드: 왼쪽 2/12(16.67%) 영역 -->
        <aside class="col-lg-2">
            <div class="flex-shrink-0" style="font-size: 16px;">
                <ul class="list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse"
                                data-bs-target="#home-collapse" aria-expanded="true">
                            <!-- 카테고리 눌렀다면 사이드바 큰 글씨로 -->
                            {% if current_category.slug %}
                            <h3>{{ current_category.slug }}</h3>
                            {% else %}
                            <!-- 카테고리를 누르지 않았다면 -->
                            <h3>전체글</h3>
                            {% endif %}
                        </button>
                        <div class="collapse show" id="home-collapse" style="">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <!-- 전체글 -->
                                <li><a href="{% url 'community:community' %}" class="link-dark rounded">전체글</a></li>
                                <!-- 카테고리 이름으로 리스트 설정 -->
                                {% for category in categories %}
                                <li><a href="{{ category.get_absolute_url }}" class="link-dark rounded">
                                    {{ category.name }}
                                </a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </aside>
        <!-- 그리드: 가운데 8/12(66.67%) 영역 -->
        <section id="post_form" class="col-lg-8">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- 유효성 검사 -->
                {% include 'form_errors.html' %}
                <!-- 편집기 크기와 맞추려고 스타일 줌 -->
                <table class="table">
                    <tr>
                        <!-- 카테고리 영역 -->
                        <td style="width: 20%;">
                            <!-- 셀렉트 옵션으로 카테고리 선택 -->
                            <select class="form-select" name="category" id="category">
                                <option value="" selected>카테고리</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </td>
                    <!-- 제목 영역 -->
                        <td style="width: 80%">
                            <!-- 폼정보가있으면(수정시)title값, 없거나기본값은'' -->
                            <input type="text" class="form-control" name="title" id="title"
                                   value="{{ form.title.value|default_if_none:'' }}" placeholder="제목을 입력해주세요">
                        </td>
                    </tr>
                    <!-- ck편집기 영역(내용, 첨부) -->
                    <tr>
                        <td colspan="2">
                            {{ form.media }}
                            {{ form.description }}
                        </td>
                    </tr>
                </table>
                <!-- 버튼 영역 -->
                <!-- 마진탑 -->
                <div id="btn" class="text-center mt-3">
                    <button type="reset" class="btn btn-primary">취소</button>
                    <a href="{% url 'community:community' %}" class="btn-a btn btn-primary">목록</a>
                    <button type="submit" class="btn btn-primary">작성</button>
                </div>
            </form>
        </section>
    </div>
</div>
{% endblock %}