GreenProject/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from greenbooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("gbook/mypage", views.mypage, name='mypage'),
    path('common/', include('common.urls')),
    path('community/', include('community.urls')),  # 커뮤니티
    path('tradebook/', include('tradebook.urls')),
    path('mypage/', include('mypage.urls')),
    path("goods/", include("goods.urls")),
    path('custom/', include('custom.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),   # 편집기
    path('price/', include('checkbookprice.urls')), # 바코드가격조회
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

GreenProject/custom/urls.py
from django.urls import path
from . import views

app_name = 'custom'

urlpatterns = [
    #http://127.0.0.1:8000/custom/
    path("", views.main, name='main'),
    #qna list
    path("qnalist/", views.qnalist, name='qnalist'),
    path("qnalist2/", views.qnalist2, name='qnalist2'),
    path("qnalist3/", views.qnalist3, name='qnalist3'),

]

GreenProject/goods/urls.py
from django.urls import path

from . import views

app_name = 'goods'


urlpatterns = [
    path('', views.goods_in_category, name='goods'),  # 구매페이지
    path('<slug:category_slug>/', views.goods_in_category, name='goods_in_category'),
    path('<int:id>/<goods_slug>/', views.goods_detail, name='goods_detail'),



    ]

GreenProject/custom/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect

# from custom.forms import PostForm
# from custom.models import Post


# Create your views here.

def main(request):
    return render(request, 'custom/hi.html')

def qnalist(request):
    return render(request, 'custom/qnalist.html')
def qnalist2(request):
    return render(request, 'custom/qnalist2.html')
def qnalist3(request):
    return render(request, 'custom/qnalist3.html')

GreenProject/templates/custom/helpedit.html
!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>공지사항</title>

    <link rel="stylesheet" href="../../static/greenbooks/css/css.css">
</head>
<body>
    <div class="board_wrap">
        <div class="board_title">
            <strong style="font-size:20rem">1:1 문의</strong>
            <p>궁금한 점을 빠르고 정확하게 안내해드립니다.  <small>(답변까지 2~3일의 시간이 소요될 수 있습니다.)</small></p>
        </div>
        <div class="board_write_wrap">
            <div class="board_write">
                <div class="title">
                    <dl>
                        <dt>제목</dt>
                        <dd><input type="text" placeholder="제목 입력" value="글 제목이 들어갑니다"></dd>
                    </dl>
                </div>
                <div class="info">
                    <dl>
                        <dt>글쓴이</dt>
                        <dd><input type="text" placeholder="글쓴이 입력" value="김이름"></dd>
                    </dl>
                    <dl>
                        <dt>비밀번호</dt>
                        <dd><input type="password" placeholder="비밀번호 입력" value="1234"></dd>
                    </dl>
                </div>
                <div class="cont">
                    <textarea placeholder="내용 입력">
글 내용이 들어갑니다.
글 내용이 들어갑니다.
글 내용이 들어갑니다.
글 내용이 들어갑니다.
글 내용이 들어갑니다.
글 내용이 들어갑니다.
글 내용이 들어갑니다.
글 내용이 들어갑니다.</textarea>
                </div>
            </div>
            <div class="bt_wrap">
                <a href="view.html" class="on">수정</a>
                <a href="view.html">취소</a>
            </div>
        </div>
    </div>
</body>
</html>

GreenProject/templates/custom/helplist-test.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



{% endblock %}

GreenProject/templates/custom/helplist.html
!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>공지사항</title>
    <link rel="stylesheet" href="../../static/greenbooks/css/css.css">
</head>
<body>
    <div class="board_wrap">
        <div class="board_title">
            <strong>공지사항</strong>
            <p>공지사항을 빠르고 정확하게 안내해드립니다.</p>
        </div>
        <div class="board_list_wrap">
            <div class="board_list">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">글쓴이</div>
                    <div class="date">작성일</div>
                    <div class="count">조회</div>
                </div>
                <div>
                    <div class="num">5</div>
                    <div class="title"><a href="view.html">글 제목이 들어갑니다.</a></div>
                    <div class="writer">김이름</div>
                    <div class="date">2021.1.15</div>
                    <div class="count">33</div>
                </div>
                <div>
                    <div class="num">4</div>
                    <div class="title"><a href="view.html">글 제목이 들어갑니다.</a></div>
                    <div class="writer">김이름</div>
                    <div class="date">2021.1.15</div>
                    <div class="count">33</div>
                </div>
                <div>
                    <div class="num">3</div>
                    <div class="title"><a href="view.html">글 제목이 들어갑니다.</a></div>
                    <div class="writer">김이름</div>
                    <div class="date">2021.1.15</div>
                    <div class="count">33</div>
                </div>
                <div>
                    <div class="num">2</div>
                    <div class="title"><a href="view.html">글 제목이 들어갑니다.</a></div>
                    <div class="writer">김이름</div>
                    <div class="date">2021.1.15</div>
                    <div class="count">33</div>
                </div>
                <div>
                    <div class="num">1</div>
                    <div class="title"><a href="view.html">글 제목이 들어갑니다.</a></div>
                    <div class="writer">김이름</div>
                    <div class="date">2021.1.15</div>
                    <div class="count">33</div>
                </div>
            </div>
            <div class="board_page">
                <a href="#" class="bt first"><<</a>
                <a href="#" class="bt prev"><</a>
                <a href="#" class="num on">1</a>
                <a href="#" class="num">2</a>
                <a href="#" class="num">3</a>
                <a href="#" class="num">4</a>
                <a href="#" class="num">5</a>
                <a href="#" class="bt next">></a>
                <a href="#" class="bt last">>></a>
            </div>
            <div class="bt_wrap">
                <a href="write.html" class="on">등록</a>
                <!--<a href="#">수정</a>-->
            </div>
        </div>
    </div>
</body>
</html> 

GreenProject/templates/custom/helpview.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>공지사항</title>
    <link rel="stylesheet" href="../../static/greenbooks/css/css.css">
</head>
<body>
    <div class="board_wrap">
        <div class="board_title">
            <strong>공지사항</strong>
            <p>공지사항을 빠르고 정확하게 안내해드립니다.</p>
        </div>
        <div class="board_view_wrap">
            <div class="board_view">
                <div class="title">
                    글 제목이 들어갑니다.
                </div>
                <div class="info">
                    <dl>
                        <dt>번호</dt>
                        <dd>1</dd>
                    </dl>
                    <dl>
                        <dt>글쓴이</dt>
                        <dd>김이름</dd>
                    </dl>
                    <dl>
                        <dt>작성일</dt>
                        <dd>2021.1.16</dd>
                    </dl>
                    <dl>
                        <dt>조회</dt>
                        <dd>33</dd>
                    </dl>
                </div>
                <div class="cont">
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다<br>
                    글 내용이 들어갑니다
                </div>
            </div>
            <div class="bt_wrap">
                <a href="list.html" class="on">목록</a>
                <a href="edit.html">수정</a>
            </div>
        </div>
    </div>
</body>
</html> 

GreenProject/templates/custom/helpwrite.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>공지사항</title>
    <link rel="stylesheet" href="../../static/greenbooks/css/css.css">
</head>
<body>
    <div class="board_wrap">
        <div class="board_title">
            <strong>공지사항</strong>
            <p>공지사항을 빠르고 정확하게 안내해드립니다.</p>
        </div>
        <div class="board_write_wrap">
            <div class="board_write">
                <div class="title">
                    <dl>
                        <dt>제목</dt>
                        <dd><input type="text" placeholder="제목 입력"></dd>
                    </dl>
                </div>
                <div class="info">
                    <dl>
                        <dt>글쓴이</dt>
                        <dd><input type="text" placeholder="글쓴이 입력"></dd>
                    </dl>
                    <dl>
                        <dt>비밀번호</dt>
                        <dd><input type="password" placeholder="비밀번호 입력"></dd>
                    </dl>
                </div>
                <div class="cont">
                    <textarea placeholder="내용 입력"></textarea>
                </div>
            </div>
            <div class="bt_wrap">
                <a href="view.html" class="on">등록</a>
                <a href="list.html">취소</a>
            </div>
        </div>
    </div>
</body>
</html>

GreenProject/templates/custom/qnalist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="board_wrap">
        <div class="board-top">
            <p class="customer_center">고객센터</p>
            <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
                <label class="btn btn-outline-primary" for="btnradio1">FAQ</label>

                <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off">
                <label class="btn btn-outline-primary" for="btnradio2">1:1 상담</label>

                <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off">
                <label class="btn btn-outline-primary" for="btnradio3">service</label>
            </div>
        </div>


        <div class="board_title">
                <strong>자주 묻는 질문 TOP 10</strong>
            <h1>회원로그인</h1>
        </div>
        <div class="board_bottom">
            <ul class="nav nav-pills nav-justified">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'custom:qnalist' %}">회원로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'custom:qnalist2' %}">상품판매</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'custom:qnalist3' %}">게시판 이용</a>
                </li>
            </ul>
            <div class="board_list_wrap">
                {% include 'custom/qnalist_content1.html'%}
            </div>
        </div>

    </div>
</div>

{% endblock %}

GreenProject/templates/custom/qnalist2.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="board_wrap">
        <div class="board-top">
            <p class="customer_center">고객센터</p>
            <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
                <label class="btn btn-outline-primary" for="btnradio1">FAQ</label>

                <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off">
                <label class="btn btn-outline-primary" for="btnradio2">1:1 상담</label>

                <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off">
                <label class="btn btn-outline-primary" for="btnradio3">service</label>
            </div>
        </div>


        <div class="board_title">
                <strong>자주 묻는 질문 TOP 10</strong>
             <h1>상품판매</h1>
        </div>
        <div class="board_bottom">
            <ul class="nav nav-pills nav-justified">
                <li class="nav-item">
                    <a class="nav-link"  href="{% url 'custom:qnalist' %}">회원로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'custom:qnalist2' %}">상품판매</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'custom:qnalist3' %}">게시판 이용</a>
                </li>
            </ul>
            <div class="board_list_wrap">
                {% include 'custom/qnalist_content2.html'%}
            </div>
        </div>

    </div>
</div>

{% endblock %}

GreenProject/templates/custom/qnalist3.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="board_wrap">
        <div class="board-top">
            <p class="customer_center">고객센터</p>
            <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                <input type="radio" class="btn-check" name="btnradio" id="btnradio1" autocomplete="off" checked>
                <label class="btn btn-outline-primary" for="btnradio1">FAQ</label>

                <input type="radio" class="btn-check" name="btnradio" id="btnradio2" autocomplete="off">
                <label class="btn btn-outline-primary" for="btnradio2">1:1 상담</label>

                <input type="radio" class="btn-check" name="btnradio" id="btnradio3" autocomplete="off">
                <label class="btn btn-outline-primary" for="btnradio3">service</label>
            </div>
        </div>


        <div class="board_title">
                <strong>자주 묻는 질문 TOP 10</strong>
            <h1>로그인 이용</h1>
        </div>
        <div class="board_bottom">
            <ul class="nav nav-pills nav-justified">
                <li class="nav-item">
                    <a class="nav-link"  href="{% url 'custom:qnalist' %}">회원로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  href="{% url 'custom:qnalist2' %}">상품판매</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'custom:qnalist3' %}">게시판 이용</a>
                </li>
            </ul>
            <div class="board_list_wrap">
                {% include 'custom/qnalist_content3.html'%}
            </div>
        </div>

    </div>
</div>

{% endblock %}

<div class="board_title">
                <strong>Q&A</strong>
                <p>자주 묻는 질문 TOP 10</p>
            </div>

GreenProject/templates/custom/qnalist_content1.html
<div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            <p class="qnatitle">Q: 회원 가입은 어떻게 하나요?</p>
        </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 홈페이지에서 회원 가입 링크를 클릭하여 필요한 개인 정보를 입력하여 회원 가입을 할 수 있습니다.</strong><br> 회원 가입은
            이메일과 비밀번호로 간편하게 진행됩니다.
            가입 후, 사용자는 개인 정보를 관리하고 주문 내역을 추적할 수 있습니다.
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingFive">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingSix">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseSix" class="accordion-collapse collapse" aria-labelledby="headingSix"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingSeven">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseSeven" class="accordion-collapse collapse" aria-labelledby="headingSeven"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingEight">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseEight" class="accordion-collapse collapse" aria-labelledby="headingEight"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingNine">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseNine" class="accordion-collapse collapse" aria-labelledby="headingNine"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>
<div class="accordion-item">
    <h2 class="accordion-header" id="headingTen">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseTen" aria-expanded="false" aria-controls="collapseTen">
            <p class="qnatitle">Q: 중고서적 검색과 구매 방법은 무엇인가요?</p>
        </button>
    </h2>
    <div id="collapseTen" class="accordion-collapse collapse" aria-labelledby="headingTen"
         data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <strong>A: 사용자는 키워드를 입력하여 중고서적을 검색하고, 구매하기 버튼을 클릭하여 구매할 수 있습니다.</strong>
            <br> 검색 결과는 관련 서적의 제목, 저자, 카테고리에 따라 표시됩니다.<br>
            ocr로 책 검색을 원하시면 검색기능에서 책의 바코드를 찍어 사진을 등록해주세요
        </div>
    </div>
</div>