GreenProject/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

GreenProject/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.community, name='community'),                            # post 리스트
    path('<int:post_id>/', views.detail, name='detail'),                    # post_id로 상세보기
    path('write/', views.post_create, name='post_create'),                  # post 작성
    path('edit/<int:post_id>/', views.post_edit, name='post_edit'),         # post 수정
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),   # post_id로 삭제
    path('category/<str:slug>/', views.category_page, name='cate_page'),    # 카테고리페이지(slug기능)
    path('likes/', views.post_like, name='post_like'),                      # 추천
]

GreenProject/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from greenbooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("gbook/mypage", views.mypage, name='mypage'),
    path('common/', include('common.urls')),
    path('community/', include('community.urls')),  # 커뮤니티
    path('tradebook/', include('tradebook.urls')),
    path('mypage/', include('mypage.urls')),
    path("goods/", include("goods.urls")),
    path('custom/', include('custom.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),   # 편집기
    path('price/', include('checkbookprice.urls')), # 바코드가격조회
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

GreenProject/custom/urls.py
from django.urls import path
from . import views

app_name = 'custom'

urlpatterns = [
    #http://127.0.0.1:8000/custom/
    path("", views.main, name='main'),
    #qna list
    path("qnalist/", views.qnalist, name='qnalist'),
    path("qnalist2/", views.qnalist2, name='qnalist2'),
    path("qnalist3/", views.qnalist3, name='qnalist3'),

]

GreenProject/goods/urls.py
from django.urls import path

from . import views

app_name = 'goods'


urlpatterns = [
    path('', views.goods_in_category, name='goods'),  # 구매페이지
    path('<slug:category_slug>/', views.goods_in_category, name='goods_in_category'),
    path('<int:id>/<goods_slug>/', views.goods_detail, name='goods_detail'),



    ]

GreenProject/mypage/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name= 'mypage'


urlpatterns = [
    path("mypage/<int:user_id>/", views.mypage, name='mypage'),
    path("memberinfo/<int:user_id>/", views.memberinfo, name='memberinfo'),
    path("membermodify/", views.membermodify, name='membermodify'),
    path("mypost/", views.mypost, name='mypost'),
    path("memo_list/", views.memo_list, name='memo_list'),
    path("memo_create/", views.memo_create, name='memo_create'),
    path("memo_delete/<int:memo_id>", views.memo_delete, name='memo_delete'),
    # path("question/", views.question, name='question'),
    # path("question_post", views.question_post, name='question_post'),
]

GreenProject/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>그린 24{% block title %}{% endblock %}</title>     <!-- 제목을 넣으면 그린 24뒤에 뜨도록 -->
    <link rel="stylesheet" href="{% static 'greenbooks/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'greenbooks/css/style.css' %}">
    <script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css"/>
    <script src="{% static 'greenbooks/js/bootstrap.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/c33abba1b7.js" crossorigin="anonymous"></script>   <!-- 임시로 내꺼 넣어놓음 -->
</head>
<body>
{% include 'header.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
{% block script %}
{% endblock %}
</body>
</html>

GreenProject/templates/footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 그린24, Inc</p>
    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>
    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'index' %}" class="nav-link px-2 text-muted">홈</a></li>
		<li class="nav-item"><a href="{% url 'community:community' %}" class="nav-link px-2 text-muted">커뮤니티</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">개인정보 처리방침</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">고객센터</a></li>
    </ul>
  </footer>
</div>

GreenProject/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

GreenProject/templates/header.html
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <h1>그린24</h1>
      </a>
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary"
        onclick="location.href='{% url 'index' %}'">홈</a></li>
        <li><a href="{% url 'goods:goods' %}" class="nav-link px-2 link-dark">구매하기</a></li>
        <li><a href="{% url 'tradebook:tradebook_list' %}" class="nav-link px-2 link-dark">중고책거래</a></li>
        <li><a href="{% url 'price:checkbookprice' %}" class="nav-link px-2 link-dark">책 가격조회</a></li>
        <li><a href="{% url 'community:community' %}" class="nav-link px-2 link-dark">커뮤니티</a></li>
        <li><a href="{% url 'custom:qnalist' %}" class="nav-link px-2 link-dark">고객센터</a></li>
      </ul>
      <div class="col-md-3 text-end">
        {% if user.is_authenticated %}
        <button type="button" class="btn btn-primary"
        onclick="location.href='{% url 'mypage:mypage' user.id %}'">마이페이지</button>

        <button type="button" class="btn btn-primary"
        onclick="location.href='{% url 'common:logout' %}'">{{ user.username }} 로그아웃</button>
        {% else %}
        <button type="button" class="btn btn-outline-primary me-2"
        onclick="location.href='{% url 'common:login' %}'">로그인</button>
        <button type="button" class="btn btn-primary"
        onclick="location.href='{% url 'common:register' %}'">회원가입</button>
        {% endif %}
      </div>
    </header>
  </div>