GreenProject/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.community, name='community'),                            # post 리스트
    path('<int:post_id>/', views.detail, name='detail'),                    # post_id로 상세보기
    path('write/', views.post_create, name='post_create'),                  # post 작성
    path('edit/<int:post_id>/', views.post_edit, name='post_edit'),         # post 수정
    path('delete/<int:post_id>/', views.post_delete, name='post_delete'),   # post_id로 삭제
    path('category/<str:slug>/', views.category_page, name='cate_page'),    # 카테고리페이지(slug기능)
    path('likes/', views.post_like, name='post_like'),                      # 추천
]

GreenProject/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from greenbooks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("gbook/mypage", views.mypage, name='mypage'),
    path('common/', include('common.urls')),
    path('community/', include('community.urls')),  # 커뮤니티
    path('tradebook/', include('tradebook.urls')),
    path('mypage/', include('mypage.urls')),
    path("goods/", include("goods.urls")),
    path('custom/', include('custom.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),   # 편집기
    path('price/', include('checkbookprice.urls')), # 바코드가격조회
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

GreenProject/goods/urls.py
from django.urls import path

from . import views

app_name = 'goods'


urlpatterns = [
    path('', views.goods_in_category, name='goods'),  # 구매페이지
    path('<slug:category_slug>/', views.goods_in_category, name='goods_in_category'),
    path('<int:id>/<goods_slug>/', views.goods_detail, name='goods_detail'),



    ]

GreenProject/mypage/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name= 'mypage'


urlpatterns = [
    path("mypage/<int:user_id>/", views.mypage, name='mypage'),
    path("memberinfo/<int:user_id>/", views.memberinfo, name='memberinfo'),
    path("membermodify/", views.membermodify, name='membermodify'),
    path("mypost/", views.mypost, name='mypost'),
    path("memo_list/", views.memo_list, name='memo_list'),
    path("memo_create/", views.memo_create, name='memo_create'),
    path("memo_delete/<int:memo_id>", views.memo_delete, name='memo_delete'),
    # path("question/", views.question, name='question'),
    # path("question_post", views.question_post, name='question_post'),
]

GreenProject/mypage/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models


# Create your models here.

class Memo(models.Model):
    content = models.TextField()
    created_date = models.DateTimeField()
    updated_date = models.DateTimeField(null=True, blank=True)









# class Question(models.Model):
#     title = models.CharField(max_length=200)
#     content = models.TextField()
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     create_date = models.DateTimeField(auto_now_add=True)
#     modify_date = models.DateTimeField(null=True, blank=True)
#     views = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.title


# class Category_product(models.Model):
#     name = models.CharField(max_length=50, unique=True)
#     slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
#
#     def __str__(self):
#         return self.name
#
#     def get_absolute_url(self):
#         return f'/product/category/{self.slug}'
#
#     class Meta:
#         ordering = ['name']
#         verbose_name = 'category'
#         verbose_name_plural = 'categories'
#
#
# class Product(models.Model):
#     name = models.CharField(max_length=300)
#     category = models.ForeignKey(Category_product, null=True, blank=True, on_delete=models.SET_NULL)
#     image = models.ImageField(upload_to='project/image/')
#     price = models.IntegerField(default=0)
#     description = models.TextField()
#     pub_date = models.DateTimeField()
#
#     def __str__(self):
#         return self.name
#
#
# class Cart(models.Model):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.IntegerField()

GreenProject/mypage/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

# from mypage.models import Question
#
#
# class MyForm(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = (
#             'title', 'content'
#         )
#         label = [
#             {'제목': 'title'},
#             {'내용': 'content'},
#
#         ]
#

GreenProject/mypage/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.utils import timezone

from common.forms import UserForm
from community.models import Post
from mypage.models import Memo


# Create your views here.
def mypage(request, user_id):
    member_list = User.objects.get(id=user_id)
    return render(request, 'mypage/mypage.html', {'member':member_list})


def memberinfo(request, user_id):
    member_info = User.objects.get(id=user_id)

    return render(request, 'mypage/memberinfo.html', {'member_info': member_info})

def membermodify(request):
    if request.method == "POST":
        user = request.user
        user.delete()
        logout(request)
        return redirect('/')
    return render(request,'mypage/memberinfo.html',)

def mypost(request):
    post = Post.objects.all().order_by('-create_date')
    post_list = post.filter(writer_id=request.user.id)
#    post_list = post.filter(liked_user=request.user.id)

    context = {'post_list': post_list}
    return render(request, 'mypage/mypost.html', context)

def memo_list(request):
    memo_list = Memo.objects.all().order_by('-created_date')
    context = {'memo_list':memo_list}
    return render(request, 'mypage/memo_list.html', context)


def memo_delete(request, memo_id):
    memo = Memo.objects.get(id=memo_id)
    memo.delete()
    return redirect('mypage:memo_list')

def memo_create(request):
    content = request.POST.get('content')
    create_date = timezone.now()
    memo = Memo(content=content, created_date=create_date)
    memo.save()

    return redirect('mypage:memo_list')




# def question(request):
#     question_list = Question.objects.order_by('-create_date')
#
#     return render(request, 'mypage/question.html',{'question_list':question_list})
# def question_detail(request):
#     pass
#
# def question_post(request):
#
#     if request.method == "POST":
#         form = MyForm(request.POST)
#         if form.is_valid():
#             question = form.save(commit=False)
#             question.author = request.user
#             question.save()
#             return redirect('question/')
#     else:
#         form = MyForm()
#
#     return render(request, 'mypage/question_post.html',{'form': form})

#### def cart(request):
#     cart_list = Cart.objects.all()
#     context = {'cart_list':cart_list }
#     return render(request, 'mypage/cart.html', context)
#
# def add_cart(request, product_id):
#     product = Product.objects.get(id=product_id)
#     cart = get_object_or_404(Cart)
#      return render(request, 'mypage/cart.html')

GreenProject/templates/mypage/cart.html
{% extends "base.html" %}
{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'greenbooks/css/bootstrap.css' %}">
    <meta charset="UTF-8">
    <title>회원정보</title>

    <style>
        #box1{height:50px;}
        a{text-decoration: none; color: black}

    </style>
</head>
<body class="m-5">
<div class="container text-center">
    <div class="d-flex flex-row mb-5">
        <div class="p-2 h3"><a href="{% url 'mypage:mypage' user.id %}">마이페이지</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memberinfo' user.id %}">회원정보</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:mypost' %}">내가쓴글</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:cart' %}">장바구니</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:question' %}">고객상담</a></div>
    </div>

    <div class="text-center">
        <p><a href="{% url 'mypage:addcart' %}">헬로헬로</a></p>
    <table class="table table-hover">
        <tr>
            <td>상품이미지</td>
            <td>상품명</td>
            <td>상품 정보</td>
            <td>가격</td>
            <td>수량</td>
        </tr>
        {% for cart in cart_list %}
        <tr>
            <td><img  width="100" height="100" src="{{ cart.product.image.url }}"></td>
            <td>{{ cart.product.name }}</td>
            <td>{{ cart.product.description }}</td>
            <td>{{ cart.product.price }}</td>
            <td>{{ cart.quantity }}</td>
        </tr>
         {% endfor %}
    </table>
    </div>
</div>
</body>
{% endblock %}
{% block script %}
{% endblock %}

GreenProject/templates/mypage/memberinfo.html
{% extends "base.html" %}
{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'greenbooks/css/bootstrap.css' %}">
    <meta charset="UTF-8">
    <title>회원정보</title>

    <style>
        #box1{height:50px;}
        a{text-decoration: none; color: black}

    </style>
</head>
<body class="m-5">
<div class="container text-center">
    <div class="d-flex flex-row mb-5">
        <div class="p-2 h3"><a href="{% url 'mypage:mypage' user.id %}">마이페이지</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memberinfo' user.id %}">회원정보</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:mypost' %}">내가쓴글</a></div>
        <div class="p-2 mx-5"><a href="">장바구니</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memo_list' %}">메모장</a></div>
    </div>
    <div class="container d-flex justify-content-center">
        <form class="justify-content-left w-50 row g-3" method="POST" id="info" action="{% url 'mypage:membermodify' %}">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <div class="col-4">
                <label for="username" class="col-form-label">아이디</label>
            </div>
            <div class="col-6">
                <input type="text" name="username" id="username" class="form-control" value="{{ member_info.username }}" readonly>
            </div>
            <div class="col-4">
                <label for="password" class="col-form-label">비밀번호</label>
            </div>
            <div class="col-6">
                <input type="password" name="password" id="password" class="form-control" value="{{ member_info.password }}" readonly>
            </div>
            <div class="col-4">
                <label for="last_name" class="col-form-label">이름</label>
            </div>
            <div class="col-6">
                <input type="text" name="last_name" id="last_name" class="form-control" value="{{ member_info.last_name }}" readonly>
            </div>
            <div class="col-4">
                <label for="email" class="col-form-label">이메일</label>
            </div>
            <div class="col-6">
                <input type="text" name="email" id="email" class="form-control" value="{{ member_info.email }}" readonly>
            </div>
            <div class="col-4">
                <label for="date" class="col-form-label">가입일</label>
            </div>
            <div class="col-6">
                <input type="text" name="email" id="date" class="form-control" value="{{ member_info.date_joined }}" readonly>
            </div>
            <div class="col-12">
                <button type="button" id="exit" class="btn btn-outline-secondary w-25 col-12">회원탈퇴</button>
            </div>
        </form>
    </div>
</div>
</body>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function() {
    $('#exit').click(function() {
        if(confirm('정말 탈퇴하시겠습니까?')) {
            $('#info').submit();
        }
    });
});
</script>
{% endblock %}

GreenProject/templates/mypage/memo_list.html
{% extends "base.html" %}
{% block content %}

{% load static %}
    <style>
        #box1{height:50px;}
        a{text-decoration: none; color: black}
    </style>
<body class="m-5">
<div class="container text-center">
    <div class="d-flex flex-row mb-5">
        <div class="p-2 h3"><a href="{% url 'mypage:mypage' user.id %}">마이페이지</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memberinfo' user.id %}">회원정보</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:mypost' %}">내가쓴글</a></div>
        <div class="p-2 mx-5"><a href="">장바구니</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memo_list' %}">메모장</a></div>
    </div>
<div class="container px-4 py-5">
    <section id="question">
            <div id="title">
                <h3 class="pb-2 border-bottom">메모장</h3>
                <h6 class="my-3">기억에 남는 책을 적어두는건 어떨까요?</h6>
            </div>

        {% if user.is_authenticated %}
        <form action="{% url 'mypage:memo_create' %}" method="POST">
            {% csrf_token %}
            <div id="btn_write" class="d-flex text-left">
            <input id="content" name="content" class="d-inline w-50 text-left"/>
                <input type="submit" class="mx-1 btn btn-primary" value="쓰기">
            </div>
        </form>
            <table class="table table-hover">
                <tbody>
                    {% if memo_list %}
                        {% for memo in memo_list %}
                        <tr class="" style="position : relative">
                            <td>{{ memo.content }}</td>
                            <td>{{ memo_list.create_date }}</td>
                                <td><a id="like" href="{% url 'mypage:memo_delete' memo.id %}" class="d-flex justify-content-evenly">
                                <i class="fa-sharp fa-solid fa-trash" style="position: absolute; bottom:15px; right: 50px"></i>
                            </a></td>
                        </tr>
                        {% endfor %}
                    <!-- post가 없으면 -->
                    {% else %}
                    <tr>
                        <td colspan="6" class="text-center">메모가 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        {% endif %}
        </section>
</div>
</div>
</body>
{% endblock %}
{% block script %}


{% endblock %}

GreenProject/templates/mypage/mypage.html
{% extends "base.html" %}
{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'greenbooks/css/bootstrap.css' %}">
    <meta charset="UTF-8">
    <title>마이페이지</title>
    <style>
        #box1{height:50px;}
        a{text-decoration: none; color: black}
    </style>
</head>
<body class="m-5">
<div class="container">
    <div class="d-flex flex-row mb-3">
        <div class="p-2 h3"><a href="{% url 'mypage:mypage' user.id %}">마이페이지</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memberinfo' user.id %}">회원정보</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:mypost' %}">내가쓴글</a></div>
        <div class="p-2 mx-5"><a href="">장바구니</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memo_list' %}">메모장</a></div>
    </div>
    <div id="box1"></div>
    <table class="table text-center">
        <thead>
            <tr>
                <th>아이디</th>
                <th>닉네임</th>
                <th>가입일</th>
            </tr>
            <tr>
                <td>{{ member.username }} </td>
                <td>{{ member.last_name }}</td>
                <td>{{ member.date_joined }}</td>
            </tr>
        </thead>
    </table>

</div>
</body>
{% endblock %}

GreenProject/templates/mypage/mypost.html
{% extends "base.html" %}
{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'greenbooks/css/bootstrap.css' %}">
    <meta charset="UTF-8">
    <title>회원정보</title>
    <style>
        #box1{height:50px;}
        a{text-decoration: none; color: black}

    </style>
</head>
<body class="m-5">
<div class="container text-center">
    <div class="d-flex flex-row mb-5">
        <div class="p-2 h3"><a href="{% url 'mypage:mypage' user.id %}">마이페이지</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memberinfo' user.id %}">회원정보</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:mypost' %}">내가쓴글</a></div>
        <div class="p-2 mx-5"><a href="">장바구니</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memo_list' %}">메모장</a></div>
    </div>
<div class="container px-4 py-5">
    <section id="mypost">
            <div id="title">
                <h2 class="pb-2 border-bottom">내가쓴글</h2>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>번호</td>
                        <td>제목</td>
                        <td>작성자</td>
                        <td>작성일</td>
                        <td>조회</td>
                        <td>추천</td>
                    </tr>
                </thead>
                <tbody>
                    {% if post_list %}
                        {% for post in post_list %}
                        <tr>
                            <td>{{ post.id }}</td>
                            <td>
                                <a href="{% url 'community:detail' post.id %}">
                                    {{ post.title }}
                                </a>
                            </td>
                            <td>{{ post.writer }}</td>
                            <td>{{ post.create_date }}</td>
                            <td>{{ post.views }}</td>
                            <td>{{ post.likes }}</td>
                        </tr>
                        {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="6" class="text-center">게시글이 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </section>
</div>
</body>
{% endblock %}

GreenProject/templates/mypage/question.html
{% extends "base.html" %}
{% block content %}

{% load static %}
    <style>
        #box1{height:50px;}
        a{text-decoration: none; color: black}
    </style>
<body class="m-5">
<div class="container text-center">
    <div class="d-flex flex-row mb-5">
        <div class="p-2 h3"><a href="{% url 'mypage:mypage' user.id %}">마이페이지</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:memberinfo' user.id %}">회원정보</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:mypost' %}">내가쓴글</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:cart' %}">장바구니</a></div>
        <div class="p-2 mx-5"><a href="{% url 'mypage:question' %}">고객상담</a></div>
    </div>
<div class="container px-4 py-5">
    <section id="question">
            <div id="title">
                <h2 class="pb-2 border-bottom">고객상담</h2>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>번호</td>
                        <td>제목</td>
                        <td>작성자</td>
                        <td>작성일</td>
                        <td>조회</td>
                    </tr>
                </thead>
                <tbody>
                    {% if question_list %}
                        {% for question in question_list %}
                        <tr>
                            <td>{{ question.id }}</td>
                            <td>
                                <a href="">
                                    {{ question.title }}
                                </a>
                            </td>
                            <td>{{ question.author }}</td>
                            <td>{{ question.create_date }}</td>
                            <td>{{ question.views }}</td>
                        </tr>
                        {% endfor %}
                    <!-- post가 없으면 -->
                    {% else %}
                    <tr>
                        <td colspan="6" class="text-center">게시글이 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        {% if user.is_authenticated %}
        <div id="btn_write" class="text-end">
            <a href="{% url 'mypage:question_post' %}" class="btn-a btn btn-primary">글쓰기</a>
        </div>
        {% endif %}
        </section>
</div>
</div>
</body>
{% endblock %}

GreenProject/templates/mypage/question_detail.html
    {% extends "base.html" %}
{% block content %}
 {% load static %}
<div class="container text-center">
  <section class="question_post w-auto">
   <h2 class="my-5">고객상담</h2>
   <form action="" method="post">
       {% csrf_token %}
    <input style="margin:0 auto;" type="text" name="title" class="form-control w-50 my-3" value="ㅎㅇㅎㅇㅎㅇ">
       <textarea style="margin:0 auto;" name="content" class="form-control w-50 my-3" rows="10"></textarea>

       {% if user.is_authenticated %}
        <div id="btn_write" class="text-center">
            <button type="submit" class="btn-a btn btn-primary">글쓰기</button>
        </div>
        {% endif %}
   </form>
  </section>
</div>


{% endblock %}

GreenProject/templates/mypage/question_post.html
    {% extends "base.html" %}
{% block content %}
 {% load static %}
<div class="container text-center">
  <section class="question_post w-auto">
   <h2 class="my-5">고객상담</h2>
   <form action="" method="post">
       {% csrf_token %}
    <input style="margin:0 auto;" type="text" name="title" class="form-control w-50 my-3" placeholder="제목을 입력해주세요">
       <textarea style="margin:0 auto;" name="content" class="form-control w-50 my-3" rows="10" ></textarea>

       {% if user.is_authenticated %}

        <div id="btn_write" class="text-center">
            <button type="submit" class="btn-a btn btn-primary">글쓰기</button>
        </div>
        {% endif %}
   </form>
  </section>
</div>


{% endblock %}